### ISSUE TITLE
Dummy images

### ISSUE THREAD

**Issue by Crissov** [babelmark/babelmark.github.io#7]
For testing image syntax `![]`, it would be nice if some simple graphic files could be referenced locally and show up in the HTML rendering. I can use external resources, of course, but that bloats the code.

Possibly useful file names (plus extensions `.png`, `.jpg`, `.svg` at least):

- `pass`, `fail`, `check`
- `example`, `sample`, `test`, `dummy`
- `image`, `picture`
- `foo`, `bar`, `baz`, `quuz`

It may be further helpful to also provide dummy text, audio and video files.

**Comment by Crissov** [comment]
I'm not sure, but something like this in `_config.yml` might work:

```` yaml
# We have several dummy images and media files available under different aliases
plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: "images/babelmark32.png"
    values:
      image: true
      redirect-from:
        - example.png
        - sample.png
        - test.png
        - dummy.png
        - image.png
        - img.png
        - picture.png
        - foo.png
        - bar.png
        - baz.png
        - quuz.png
        - pass.png
        - fail.png
        - check.png
````
